# Generated by Django 3.1.3 on 2020-12-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='month',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='changes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='changes',
            name='person',
        ),
        migrations.AlterField(
            model_name='changes',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budget.expenses'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Energie', 'Energie en voorzieningen'), ('Telecom', 'Telecom'), ('Onderdak', 'Onderdak'), ('Transport', 'Transport'), ('Levensmiddelen', 'Levensmiddelen'), ('Verzekering', 'Verzekering'), ('Schuld', 'Schuld'), ('Entertainment', 'Entertainment'), ('Gezondheid', 'Gezondheid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='category',
            field=models.CharField(choices=[('Maandelijks', 'Maandelijks'), ('Wekelijks', 'Wekelijks'), ('Eenmalig', 'Eenmalig')], max_length=100),
        ),
    ]
